mediamind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/urls.py
from django.urls import path
from .views import index, new_contact, service_detail

app_name = 'services'
urlpatterns = [
    path('contact_new/', new_contact, name='contact_new'),
    path('<service_slug>/', service_detail, name='service_detail'),
    path('', index, name='index'),
]

services/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, null=True)

    def __str__(self):
        return self.name

    def __len__(self):
        return len([i for i in self.service_set.all()])

    class Meta:
        verbose_name_plural = 'Categories'


class Service(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True)
    price = models.PositiveIntegerField(blank=True, null=True)
    description = models.TextField()
    image = models.ImageField(upload_to='services/', blank=True, null=True)

    def __str__(self):
        return self.name


class ContactRequest(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=100)

    def __str__(self):
        return self.name

services/forms.py
from django import forms
from .models import ContactRequest


class ContactRequestForm(forms.ModelForm):
    class Meta:
        model = ContactRequest
        fields = ['name', 'email', 'phone']
        labels = {'name': "", 'email': "", 'phone': ""}
        widgets = {'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваше полное имя *'}),
                   'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваша электронная почта *'}),
                   'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш номер телефона *'})}

services/views.py
from django.shortcuts import render, redirect
from .models import Service, Category
from .forms import ContactRequestForm
from django.core.mail import send_mail


def index(request):
    services = Service.objects.all()
    categories = Category.objects.all()[:9]
    contact_form = ContactRequestForm()
    context = {'services': services, 'categories': categories, 'contact_form': contact_form}
    return render(request, 'index.html', context)


def new_contact(request):
    """Create new contact form"""
    if request.method == "POST":
        form = ContactRequestForm(data=request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            email_address = contact.email
            subject = 'Contact request'
            message = "Thank you for leaving request. We will contact you soon"
            send_mail(subject, message, 'mediamind@gmail.com', [email_address])
            contact.save()
            return redirect('services:index')


def service_detail(request, service_slug):
    service = Service.objects.get(slug=service_slug)
    categories = Category.objects.all()[:10]
    last_services = Service.objects.all()
    context = {'service': service, 'categories': categories, 'last_services': last_services}
    return render(request, 'service_detail.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <!-- <meta name="theme-color" content="#1e1043"> -->
    <meta name="theme-color" content="#000">
    <meta name="msapplication-navbutton-color" content="#000">
    <meta name="apple-mobile-web-app-status-bar-style" content="#000">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="QIBRAy, Санаторий">
    <link rel="shortcut icon" href="{% static 'images/Logo png 2.png' %}" />
    <title>Media Mind - digital agency</title>
    <!-- ===========CCЫЛКИ================= -->
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.css" />
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />

    <script src="https://unpkg.com/swiper/swiper-bundle.js"></script>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>
    <!-- ===========ШРИФТЫ================= -->

    <!-- ============================================== -->


    <link rel="stylesheet" href="{% static 'css/style-min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <script defer src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script defer src="{% static 'js/script.js' %}"></script>

    <script src="{% static 'js/wow.min.js' %}"></script>
    <script>
        new WOW({
            mobile: false,
            live: true    // default
        }).init();
    </script>

<style type="text/css">
        .section1,
        .market,
        .uslugi,
        footer {
            background: url({% static 'images/bg.png' %}) 50% 50% / cover;
            background-attachment: fixed;
        }
    </style>
</head>

<body>
    <div id="scroll-percentage">
        <div class="percentage"></div>
    </div>
    <div id="js-preloader" class="js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <section class="section1">
        <div class="container">
            <header class="header1">
                <div class="logo">
                    <img src="{% static 'images/Logo png 2.png' %}" alt="">
                </div>
                <div class="menu1">
                    <ul>
                        <li>
                            <a href="#">Главная</a>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <a href="#">О нас</a>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <a href="#">Услуги</a>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <a href="#">Контакты</a>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <a href="">+998 33 987 32 87</a>
                        </li>
                    </ul>
                </div>
                <div class="phone_menu">
                    <h5>Menu</h5>
                    <div class="menu_ico">
                        <div></div>
                        <div></div>
                        <div></div>
                    </div>
                </div>
                <div class="menu2">
                    <a href="">
                        <ul>
                            <li>
                                <h5>Главная</h5>
                            </li>
                        </ul>
                    </a>
                    <a href="#">
                        <ul>
                            <li>
                                <h5>О нас</h5>
                            </li>
                        </ul>
                    </a>
                    <a href="#">
                        <ul>
                            <li>
                                <h5>Услуги</h5>
                            </li>
                        </ul>
                    </a>
                    <a href="#">
                        <ul>
                            <li>
                                <h5>Контакты</h5>
                            </li>
                        </ul>
                    </a>
                </div>
            </header>


            {% block content %}

            {% endblock content %}

           <footer>
        <div class="container">
            <div class="footer_left col-lg-6">
                <div class="logo">
                    <img src="img/Logo png 2.png" alt="">
                </div>
                <div>
                    <p>Далеко-далеко за словесными горами, в стране гласных и согласных живут рыбные тексты. Дороге
                        составитель наш что несколько рот lorem своего осталось пустился использовало. Если, продолжил
                        вдали большого то пустился текстами решила злых!</p>
                    <p>Made by "Media Mind"</p>
                </div>
            </div>
            <div class="footer_right col-lg-6">
                <iframe
                    src="https://yandex.ru/map-widget/v1/?um=constructor%3A43a4ee39b8df33750f9e5805475f1aa1fe0e66b93de99b884d1de5c95276761e&amp;source=constructor"
                    width="350" height="240" frameborder="0"></iframe>
            </div>
        </div>
    </footer>



    <!-- ============================================== -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'js/parallax.min.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>



</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<div class="main_text">
                <div class="main_h1 col-lg-6">
                    <h1 class="wow slideInUp">Media Mind</h1>
                    <h2 class="wow fadeInUp" data-wow-delay="0.2s">Развивай свой бизнес с нами</h2>
                    <h3 class="wow fadeInUp" data-wow-delay="0.3s">Десятки успешно закрытых кейсов
                        развеят все ваши сомнения!</h3>
                    <a class="wow fadeInUp" data-wow-delay="0.4s" href="#">Свяжитесь с нами</a>
                </div>
                <div class="main_img col-lg-6">
                    <img src="{% static 'images/Online ads-amico 1.png' %}" alt="">
                </div>

            </div>
            <div class="agency_text">
                <h4 class="wow fadeInUp" data-wow-delay="0.5s">Агенство Интеренет Маркетинга в Ташкенте и по всему Узбекистану.</h4>
            </div>
            <div class="uslugi_tags">
                <div class="tags_text col-lg-5">
                    <h4 class="wow fadeInUp" data-wow-delay="0.6s">Предлагаем комплексные услуги
                        интернет маркетинга в Ташкенте.</h4>
                    <div class="tags_line"></div>
                </div>
                <div class="tags col-lg-7">
                    {% for category in categories %}
                        <a class="tag">{{ category.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <section class="result">
        <div class="container">
            <div class="result_text col-lg-6">
                <h2 class="wow fadeInUp" data-wow-delay="0s">С нами - результат
                    гарантирован</h2>
                <p class="wow fadeInUp" data-wow-delay="0.1s">Каждому клиенту мы гарантируем окупаемость расходов
                    на маркетинг и реальные результаты от продвижения в виде
                    продаж, посещений, клиентов, увеличения продаж и популярности.</p>
                <a class="wow fadeInUp" data-wow-delay="0.2s" href="#">Получить консультацию</a>
            </div>
            <div class="resul_img col-lg-6 wow fadeInRight"><img src="{% static 'images/Mobile Marketing-bro 1.png' %}" alt=""></div>
        </div>
    </section>

    <section class="uslugi parallax-window" data-parallax="scroll" data-image-src="{% static 'images/bg.png' %}">
        <div class="container">
            <h3>Мы предлагаем следующие услуги :</h3>
            <div class="uslugi_div">
                <!-- ЦИКЛ ОТСЮДА -->
                {% for service in services %}
                <div class="usluga">
                    <img src="{{service.image.url}}" alt="{{ service.name }}">
                    <div class="usluga_div">
                        <div class="uslu_div">
                            <h4>{{ service.name}}</h4>
                        <p>{{ service.description|truncatewords:25 }}</p>
                        </div>

                        <div>
                            <a href="{% url 'services:service_detail' service.slug %}">Подробнее</a>
                            <a href="">Заказать</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                <!-- ДО СЮДА -->


            </div>
        </div>
    </section>
    <section class="last">
        <div class="container">

            <h3>Наши последние работы :</h3>

            <div class="last_div">
                <div class="last_text">
                    <h4>Магазин косметики</h4>
                    <p>Как мы повысили продажи сети магазинов
                        косметики в 90 раз за 3 года и увеличили
                        годовую выручку с 45 000$ до 2.5 миллиона $.</p>
                    <a href="#">Посмотреть</a>
                </div>
                <div class="last_text">
                    <h4>Магазин косметики</h4>
                    <p>Как мы повысили продажи сети магазинов
                        косметики в 90 раз за 3 года и увеличили
                        годовую выручку с 45 000$ до 2.5 миллиона $.</p>
                    <a href="#">Посмотреть</a>
                </div>
                <div class="last_text">
                    <h4>Магазин косметики</h4>
                    <p>Как мы повысили продажи сети магазинов
                        косметики в 90 раз за 3 года и увеличили
                        годовую выручку с 45 000$ до 2.5 миллиона $.</p>
                    <a href="#">Посмотреть</a>
                </div>

            </div>

            <a href="#">Смотреть еще</a>

        </div>
    </section>
    <section class="market parallax-window" data-parallax="scroll" data-image-src="./img/bg.png">
        <div class="container">
            <div class="result_text col-lg-6">
                <h2>Вы нашли маркетолога, который
                    начнет приносить вам прибыль!</h2>
                <p>До работы с нами, многие наши клиенты теряли сотни долларов
                    на рекламу в интернете и услуги псевдо маркетологов,
                    не получая от этого ощутимой отдачи.

                    С нами вам не придется волноваться за результативность
                    и окупаемость вложений в маркетинг, мы работали с самыми
                    разными отрослями B2B и B2C, на опытах наших клиентов
                    убедились в том, что с помощью интернет маркетинга можно
                    продавать любой тип продукции, продвигать любые виды
                    услуг и предложений.
                </p>
            </div>
            <div class="resul_img col-lg-6"><img src="{% static 'images/Sponsor-rafiki 1.png' %}" alt=""></div>
        </div>
    </section>

    <section class="form">

        <div class="container">

            <h3>Наши контакты:</h3>
            <p>Свяжитесь с нами сами или оставьте <br>
                свои контактные данные, чтобы мы <br>
                связались с вами сами.</p>

            <div class="form_div">

                <div class="form_text">
                    <h4>+998 33 987 32 87</h4>
                    <p>Узбекистан, Ташкент, улица Алишера Навои</p>
                    <div class="sm">
                        <a href=""></a><a href=""></a><a href=""></a>
                    </div>
                </div>
                <div class="form_input">
                    <form method="post" action="{% url 'services:contact_new' %}">
                        {% csrf_token %}
                        {{ contact_form.as_p }}
                        <button name="submit">Отправить</button>
                    </form>
                </div>

            </div>

        </div>

    </section>




{% endblock content %}

templates/service_detail.html
{% extends 'base.html' %}

{% block content %}





            <div class="usluga_podrobno">
                <div class="left_bar col-sm-4">
                    <div class="bar">
                        <img src="img/osnovnie-vidi-internet-reklami.jpg" alt="">
                        <div class="bar_tags">
                            <h3>Другие категории:</h3>
                            <div class="bar_tag_div">
                                {% for category in categories %}
                                    <a href="#" class="tag_div">{{ category.name }}</a>
                                {% endfor %}
                            </div>
                            <h3>остальные услуги:</h3>
                            <div class="bar_usl">
                                {% for last_service in last_services %}
                                    <a href="#" class="usl">{{ last_service.name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="usluga_info col-sm-8">
                    <div class="usl_podr">
                        <img src="{{ service.image.url }}" alt="">
                        <h2>{{ service.name }}</h2>

                        <p>{{ service.description }}</p>

                        <h3> {{ service.price }}<span>сум</span></h3>

                        <a href="{% url 'services:index' %}">Заказать</a>
                    </div>
                </div>
            </div>
        </div>
    </section>





{% endblock content %}